databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user

services:
  - type: web
    name: django-ecommerce
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
      - key: RENDER_EXTERNAL_HOSTNAME
        value: your-app-name.onrender.com